netsite/aboutapp/urls.py
from django.urls import path
from . import views

app_name = "aboutapp"

urlpatterns = [    
  path("", views.about), 
  path('aboutapp/', views.about),
]

netsite/calcapp/urls.py
from django.urls import path
from . import views

app_name = "calcapp"

urlpatterns = [    
  path("", views.result), 
  path('calcapp/', views.result),
]

netsite/contactapp/urls.py
from django.urls import path
from . import views

app_name = "contactapp"

urlpatterns = [    
  path("", views.contact), 
  path('contactapp/', views.contact),
]

netsite/foliumapp/urls.py
from django.urls import path
from . import views

app_name = "foliumapp"

urlpatterns = [    
  path("", views.foliumm), 
  path('foliumapp/', views.foliumm),

]

netsite/netapp/urls.py
# netapp/urls.py

from django.urls import path
from . import views

app_name = "netapp"

urlpatterns = [
  path("", views.index),
  path('netapp/', views.index),
]

netsite/netsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from netapp import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('netapp/', include('netapp.urls')),
    path('postapp/',include('postapp.urls')),
    path('posttwoapp/',include('posttwoapp.urls')),
    path('aboutapp/',include('aboutapp.urls')),
    path('contactapp/',include('contactapp.urls')),
    path('foliumapp/',include('foliumapp.urls')),
    path('users/',include('users.urls')),
    path('users/signup/',include('users.urls')),
    path('calcapp/', include('calcapp.urls')),
]

netsite/postapp/urls.py
from django.urls import path
from . import views

app_name = "postapp"

urlpatterns = [    
  path("", views.post), 
  path('postapp/', views.post),
]

netsite/posttwoapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = "posttwoapp"

urlpatterns = [    
  path("", views.posttwo), 
  path("posttwoapp/", views.posttwo),
]

netsite/users/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path
from views import *
import users.views
from django.contrib.auth import login as auth_login

urlpatterns = [
    path('users/', include('users.urls')),
] 

app_name = "users"
urlpatterns = [
  path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
  path("", views.login), 
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.signup, name='signup'),
]

netsite/calcapp/models.py
from django.db import models

# Create your models here.

netsite/netapp/models.py
from django.db import models
from django.contrib import admin

netsite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

netsite/aboutapp/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
  return render(request, 'aboutapp/about.html')

netsite/calcapp/views.py
from django.shortcuts import render,redirect

# Create your views here.

def result(request):
  calc()
  return render(request, 'calcapp/calc.html')

def calc():
  return calc

def eat1(request):
    riceCarbon = 0.5
    rice = int(request.GET.get('rice'))
    context = {
        'rice': rice,
    }
    return rice * riceCarbon

netsite/contactapp/views.py
from django.shortcuts import render

# Create your views here.
def contact(request):
  return render(request, 'contactapp/contact.html')

netsite/foliumapp/views.py
from django.shortcuts import render
import csv
import json
import os
import webbrowser

import folium
import numpy as np
import pandas as pd
import requests
from django.shortcuts import render
from folium import plugins
from pandas.io.json import json_normalize
from folium.plugins import HeatMap
  
def show_map():
  csvFile = 'foliumapp/Si_do.csv'
  SiDodf = pd.read_csv(csvFile, encoding='utf-8')
  jsonFile = 'foliumapp/Sidojson.json'
  Sido_geo = json.load(open(jsonFile, encoding='utf-8'))
  
  m=folium.Map(location=[36.45,127.42],title="OpenStreetMap",zoom_start=20)
  folium.Choropleth(
    geo_data=Sido_geo,
    name="carbonmap",
    data=SiDodf,
    columns=['Sido','carbon'],
    key_on='feature.properties.CTP_ENG_NM',
    fill_color='PuRd',
    fill_opacity=0.7,
    legend_name='carbonmap').add_to(m)
  folium.LayerControl().add_to(m)
  
  m.save('foliumapp/map.html')

def foliumm(request):
  show_map()
  return render(request, 'foliumapp/map.html')

netsite/netapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
  return render(request, 'netapp/index.html')

netsite/postapp/views.py
import csv
import json
import os
import webbrowser

import folium
import numpy as np
import pandas as pd
import requests
from django.shortcuts import render
from folium import plugins
from pandas.io.json import json_normalize

def post(request):
  return render(request, 'postapp/post.html')

netsite/posttwoapp/views.py
from django.shortcuts import render

# Create your views here.
def posttwo(request):
  return render(request, 'posttwoapp/post2.html')

'''def my_view(request):
  if request.method == 'POST':
    checksave = request.POST.getlist('checksave')
    print(checksave)
  return render(request, 'post2.html')

def input_test(request):
  if request.POST:
    list_item = request.POST.getlist('test')
    print(list_item)'''
    

netsite/users/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from users.forms import UserForm

# Create your views here.
def login(request):
  if request.method == "POST":
    username = request.POST['username']
    password = request.POST['password']
    user = auth.authenticate(request, username=username, password=password)
    if user is not None:
      auth.login(request, user)
      return redirect('/')
  else:
    return render(request, 'users/login.html', {'error': 'username or password is incorrect'})
  return render(request, 'users/login.html')

@csrf_exempt
def search(request):
  return HttpResponse('success')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            auth.login(request,user)  # type: ignore # 로그인
            return redirect('/')
    else:
      form = UserForm()
      return render(request, 'users/signup.html', {'form': form})

""" def signup(request):
    if request.method == 'POST':
      if request.POST['password'] == request.POST['password']:
        user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
        auth.login(request, user)
        return redirect('/')
    return render(request, 'users/signup.html') """

def logout(request):
  if request.method == 'POST':
    auth.logout(request)
    return redirect('/')
  return render(request,'netapp/index.html')

netsite/calcapp/templates/calcapp/calc.html
<style>
  h2{
    color: blue;
  }
</style>
<h1>결과는</h1>
<h2>5.312 kgCO2eq</h2>
{{result}}입니다.

netsite/posttwoapp/templates/posttwoapp/post2.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Welcome to Net-Zero</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        </head>
        <!--<script>
          $(function(){
              setTimeout(function(){
                var output='';
                $('input:checked').each(function(index,item){
                  output += $(item).val()+',';
              });
              alert('나는 오늘 '+output.substring(0,output.length-3)+'');
            }, 3000);
        });
        </script>-->

        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@600&family=Nanum+Gothic:wght@700&family=Nanum+Myeongjo&family=Poor+Story&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css2?family=Poor+Story&display=swap" rel="stylesheet">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles_posttwo.css' %}" rel="stylesheet" />
        {%bootstrap_css%}
        {%bootstrap_javascript%}
        <style>

          input[type="number"], #checksave {
            width: 50px;
            height: 20px;
            padding: 1px;
            line-height: 15px;
            margin: 3px 0;
            box-sizing: border-box;
          }

          input[type=checkbox] {
            accent-color: green;
            width: 15px;
            height:15px;
          }
          .check{
            padding: 20px 20px;
            background-color: lightyellow;
            border-radius: 5%;
          }
          .check h1{
            background-color: rgb(255, 255, 124);
            background-size: 50%;
            padding: 0px 20px;
            text-align: center;
          }
          #check_in{
            line-height:40px;
            
          }

          .checksaveClass{
            font-size: 15px;
            line-height:30px;
            text-align: center;
          }
          .loginorlogout, .signClass{
            text-align: center;
          }

          .loginorlogout button, .signClass button{
            text-align: center;
            background-color: green;
            color: white;
            outline: 0;
          }

        </style>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/netapp">Net-Zero</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/netapp">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/aboutapp">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/contactapp">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../../static/assets/img/6166906.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1 style="font-height: bold;">나의 탄소 다이어리📝
                            </h1>
                            <h2 class="subheading">스스로 하루 탄소소비에 대해 기록하면서
                                <br> 탄소중립운동에 참여해봅시다~</h2>
                            <span class="meta">
                                
                                <a href="#!"></a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class = "loginorlogout">
                            {% if user.is_authenticated %}
                            <a href = "{% url 'users:logout' %}">{{user.username}}로그아웃</a>
                            <span>||</span>
                            {%else%}
                            <button type = "submit" value="로그인" class="btn btn-primary" onclick="location.href='/users'">로그인</button>
                            {% endif %}
                        </div>
                        <div class ="signClass">
                          {% if not user.is_authenticated %}
                          <a href='/users/signup' value="회원가입" class="sign">회원가입</a>
                          {% endif %}
                      </div>
                      <div class = "check">
                        <h1>✔체크리스트✔</h1>
                        <form action="/netsite/calcapp/views.py" method="GET" id = "check_in">
                          {% csrf_token %}
                            <input type ="checkbox" name = "eat1" value ="on"> 밥을 <input type="number" name="rice" min="0" max="10" value="0" step ="0.5">공기를 섭취했다. (0.5인분부터!)
                            <br>
                            <input type ="checkbox" name = "eat2" value ="on"> 계란을 <input type="number" name="egg" min="0" max="30" value="0">개를 섭취했다.
                            <br>
                            <input type ="checkbox" name = "eat3" value ="on"> 고기를
                            <select name ="eat_select">
                                <option value = "cow"> 소 </option>
                                <option value = "pig"> 돼지 </option>
                                <option value = "chicken"> 닭 </option>
                            </select>을
                            <input type="number" name="meat" min="0" max="30" value="0" step ="0.5">인분을 섭취했다.(0.5인분부터!)
                            
                            <br>
                            <input type ="checkbox" id ="cafe" name = "eat4" value ="on"> 커피를 <input type="number" name="coffee" min="0" max="3000" value="0" step ="10">ml을 섭취했다.
                            <label for="cafe">
                            </label>
                            <br>
                            <input type ="checkbox" name = "activity1" value ="on"> 교통수단
                            <select name ="trans">
                                <option value = "car"> 자가용 </option>
                                <option value = "car"> 지하철 </option>
                                <option value = "car"> 버스 </option>
                            </select>을
                            <input type="number" name="trans_min" min="0" max="1440" value="0" step ="1">분 이용했다.
                            <br>
                            <input type ="checkbox" name = "activity2" value ="on"> 쓰레기를 <input type="number" name="trash" min="0" max="50" value="0" step ="1">L을 배출했다. 
                            <br>
                            <input type ="checkbox" name = "activity3" value ="on"> 전자기기
                            <select name ="device">
                                <option value = "note"> 노트북 </option>
                                <option value = "computer"> 컴퓨터 </option>
                                <option value = "smart"> 스마트폰 </option>
                                <option value = "tv"> TV </option>
                            </select>을
                            <input type="number" name="device_min" min="0" max="1440" value="0" step ="1">분 이용했다.
                            <br>
                            <input type ="checkbox" name = "activity4" value ="on"> 화장실을 <input type="number" name="toilet" min="0" max="30" value="0" step ="1">번 사용했다. 
                            <br>
                            <input type ="checkbox" name = "elec1" value ="on"> 전등을 <input type="number" name="light_min" min="0" max="1440" value="0" step ="1">분 켜두었다.
                            <br>
                            <input type ="checkbox" name = "elec2" value ="on"> 보일러 사용을 <input type="number" name="heat_min" min="0" max="1440" value="0" step ="1">분 사용했다.
                            <br>
                            <input type ="checkbox" name = "elec3" value ="on"> 샤워를  <input type="number" name="water_min" min="0" max="1440" value="0" step ="1">분 했다.
                            <br>
                            <br>
                            <div class="checksaveClass">
                                <lable for ="checksave"> 👇체크 한번 더 확인하고 저장 버튼을 눌러주세요!👇</label>
                                <br>
                                <button id="checksave" name = "save" value="저장" onclick = "javascript:btn()" >저장</button>
                                <div id="result"></div>
                            </div>
                        </form>
                        <br>
                        <br>
                        <h1>오늘 내가 소비한 탄소는?</h1>
                        <iframe id= 'calc' src = '/calcapp' title ="calc" width="150%" height="200px"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </article>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; ELEVEN </div>
                    </div>
                </div>
            </div>
        </footer>
        <script>
          function btn(){
              alert('저장되었습니다!');
          }
          </script>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src='{% static "js/scripts.js" %}'></script>
    </body>
</html>

netsite/users/templates/users/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Base</title>
  {%bootstrap_css%}
  {%bootstrap_javascript%}
</head>
<body>
  <div class = "login_base">
    <label>사용자</label>
    <input type = "text" name = "username" id = "username">
</div>
<div>
    <label>비밀번호</label>
    <input type = "text" name = "password" id = "password">
</div>
<button type = "submit" value="로그인" class="btn btn-primary">로그인</button>
</body>
</html>

netsite/users/templates/users/form_errors.html
<!-- users>form_errors.html -->

{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}

<!-- 필드 오류 출력 -->
<div>
    <strong>{{field.label}}</strong>
    {{error}}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}

<!-- 넌필드 오류 출력 -->
<div>
    <strong>{{error}}</strong>
</div>
{% endfor %}
{% endif %}

netsite/users/templates/users/header.html
<!-- header.html : 로그인/로그아웃 버튼 만들기 -->
<div style = "text-align:center; margin: 2rem 0; ;" >
  <div>
      <h1 style = "font-family: 'BIZ UDGothic', sans-serif;">Pragmatic</h1>
  </div>
  <div>
      <span>nav1</span>
      <span>nav2</span>
      <span>nav3</span>

      {% if not user.is_authenticated %}
<!--     login하고 나서 그다음에 연결되어야 하는 경로를 next로 적어준다. -->
      <a href = "{% url 'users : login' %}?next ={{ request.path }}" >
          <span>login</span>    
      </a>
      {% else %}
      <a href = "{% url 'users : logout' %}?next ={{ request.path }}">
          <span>logout</span>    
      </a>
      {% endif %}
  </div>
</div>

netsite/users/templates/users/login.html
{% load django_bootstrap5 %}
{% block content %}
<link href="https://fonts.googleapis.com/css2?family=Poor+Story&display=swap" rel="stylesheet">
<style>
  h1{
    color: green;
    text-align: center;
    font-family: "Poor Story", -apple-system, BlinkMacSystemFont;
  }
  h3{
    text-align: center;
    font-family: "Poor Story", -apple-system, BlinkMacSystemFont;
  }
  

  .idclass, .pwclass{
    text-align: center;
    font-family: "Poor Story", -apple-system, BlinkMacSystemFont;
    
  }

  .loginclass{
    text-align: center;
  }
  .loginclass button{
    border-radius: 10%;
    color: white;
    text-align: center;
    background-color: green;
    font-family: "Poor Story", -apple-system, BlinkMacSystemFont;
    padding: 5px 10px;
  }

</style>
<h1>로그인</h1>
<h3>아이디와 비밀번호를 정확히 입력해주세요.</h3>
<form method = "post" action = "{% url 'users:login' %}">
    {% csrf_token %}
    {% include 'users/form_errors.html' %}
    <div class="idclass">
        <label>사용자ID</label>
        <input type = "text" name = "username" id = "username">
    </div>
    <div class="pwclass">
        <label>비밀번호</label>
        <input type = "text" name = "password" id = "password">
    </div>
    <br>
    <div class="loginclass">
    <button type = "submit" value="로그인" class = "btn btn-primary" >로그인</button>
    </div>
</form>

{% endblock %}

netsite/users/templates/users/menu.html
{% if user.is_authenticated %}

<a href="{%url 'users:logout'%">{{user.username}}님 로그아웃</a>
<span>||</span>
{% else %}
<a href="{%url 'users:login'%}"로그인></a>
{% endif %}
<a href="{%url 'users:signup'%">회원가입</a>
{% endif %}

netsite/users/templates/users/signup.html
{% load django_bootstrap5 %}
{% block content %}
<link href="https://fonts.googleapis.com/css2?family=Poor+Story&display=swap" rel="stylesheet">
<style>
  h1{
    text-align: center;
    font-family: "Poor Story", -apple-system, BlinkMacSystemFont;
  }
  h3{
    color: green;
    text-align: center;
    font-family: "Poor Story", -apple-system, BlinkMacSystemFont;
  }
  .mb-3{
    text-align: center;
    font-family: "Poor Story", -apple-system, BlinkMacSystemFont;
    
  }
  .create button{
    border-radius: 10%;
    color: white;
    text-align: center;
    background-color: green;
    font-family: "Poor Story", -apple-system, BlinkMacSystemFont;
    padding: 5px 10px;
  }
</style>
<div class="wrapper" style="text-align: center;">
  <div class="container my-3">
    <form method="post" action="{% url 'users:signup'%}">
        {% csrf_token %}
        {% include "users/form_errors.html" %}
        <div class="mb-3">
            <h1>회원가입하기</h1>
            <h3>탄소중립 캠페인 함께해요🙋‍♀️</h3>
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                    value="{{form.username.value|default_if_none:''}}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                    value="{{form.password1.value|default_if_none:''}}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                    value="{{form.password2.value|default_if_none:''}}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                    value="{{form.email.value|default_if_none:''}}">
        </div>
        <div class="create">
        <button type="submit" class="btn btn-primary">생성하기</button></div>
    </form>
</div>
{% endblock %}